server:
 port: 8084
 
spring:
 application:
  name: zuul-server


eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
 serviceurl:
  defaultzone: http://localhost:8083/eureka/


management:
 endpoints:
  web:
   exposure:
    include: "*"


# Hardcode service    
#    
#zuul:
# routes:
#  my-service:
#   path: /my-service/**
#   url: http://localhost:8080/

# Expose Headers
zuul:
 sensitiveHeaders: Cookie,Set-Cookie

